
package sinonimos;

/**
 *
 * @author spinelli
 */


import javax.swing.JButton;

import javax.swing.JTable;

import javax.swing.JTextField;



import sinonimos.OptionPane;

import javax.swing.table.DefaultTableModel;

public class DiccionarioGUI extends java.awt.Dialog
{
    @SuppressWarnings("compatibility:3444021626500921871")
    private static final long serialVersionUID = -5971378675848143724L;

    /** Creates new form DiccionarioGUI */
    public DiccionarioGUI(java.awt.Frame parent, boolean modal)
    {
        super(parent, modal);
        initComponents();
    }

    private transient OptionPane optionPane = new sinonimos.DefaultOptionPane();

    public void setOptionPane(OptionPane o)
    {
        this.optionPane = o;
    }

    public OptionPane getOptionPane()
    {
        return this.optionPane;
    }

    /* Estos Metodos getXXXX() se incluyen para desarrollar la prueba GUI accediendo
     * directamente a la GUI por componente, sin usar robot o los nombres
     * de los campos, no serian necesarios de usar alguna de de estas
     * alternativas
     */

    public JButton getBoton_Agregar()
    {
        return Boton_Agregar;
    }

    public JButton getBoton_Buscar()
    {
        return Boton_Buscar;
    }

    public JButton getBoton_Eliminar()
    {
        return Boton_Eliminar;
    }

    public JTable getTabla_Sinonimos()
    {
        return Tabla_Sinonimos;
    }

    public JTextField getTexto_Busqueda()
    {
        return Texto_Busqueda;
    }

    public JTextField getTexto_Clave()
    {
        return Texto_Clave;
    }

    public JTextField getTexto_Sinonimo()
    {
        return Texto_Sinonimo;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    
    private void initComponents() {//GEN-BEGIN:initComponents

        Boton_Agregar = new javax.swing.JButton();
        Boton_Eliminar = new javax.swing.JButton();
        Texto_Clave = new javax.swing.JTextField();
        Texto_Sinonimo = new javax.swing.JTextField();
        LabClave = new javax.swing.JLabel();
        LabSin = new javax.swing.JLabel();
        LabBusqueda = new javax.swing.JLabel();
        PanelBusqueda = new javax.swing.JPanel();
        LabTextBusqueda = new javax.swing.JLabel();
        Texto_Busqueda = new javax.swing.JTextField();
        Boton_Buscar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla_Sinonimos = new javax.swing.JTable();

        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                closeDialog(evt);
            }
        });

        Boton_Agregar.setText("Agregar");
        Boton_Agregar.setName("Boton_Agregar"); // NOI18N
        Boton_Agregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_AgregarActionPerformed(evt);
            }
        });

        Boton_Eliminar.setText("Eliminar");
        Boton_Eliminar.setName("Boton_Eliminar"); // NOI18N
        Boton_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_EliminarActionPerformed(evt);
            }
        });

        Texto_Clave.setName("Texto_Clave"); // NOI18N

        Texto_Sinonimo.setName("Texto_Sinonimo"); // NOI18N

        LabClave.setText("Clave");

        LabSin.setText("Sinonimo");

        LabBusqueda.setText("Busqueda");
        LabBusqueda.setToolTipText("");

        LabTextBusqueda.setText("Criterio");

        Texto_Busqueda.setMinimumSize(new java.awt.Dimension(100, 19));
        Texto_Busqueda.setName("Texto_Busqueda"); // NOI18N

        Boton_Buscar.setText("Buscar");
        Boton_Buscar.setName("Boton_Buscar"); // NOI18N
        Boton_Buscar.setVerifyInputWhenFocusTarget(false);
        Boton_Buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_BuscarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout PanelBusquedaLayout = new javax.swing.GroupLayout(PanelBusqueda);
        PanelBusqueda.setLayout(PanelBusquedaLayout);
        PanelBusquedaLayout.setHorizontalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addComponent(LabTextBusqueda)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Texto_Busqueda, javax.swing.GroupLayout.DEFAULT_SIZE, 251, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Boton_Buscar, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        PanelBusquedaLayout.setVerticalGroup(
            PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBusquedaLayout.createSequentialGroup()
                .addGap(5, 5, 5)
                .addGroup(PanelBusquedaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Texto_Busqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabTextBusqueda)
                    .addComponent(Boton_Buscar))
                .addGap(1, 1, 1))
        );

        jScrollPane1.setViewportView(Tabla_Sinonimos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 160, Short.MAX_VALUE)
                        .addComponent(LabBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(167, 167, 167))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(LabClave)
                                .addGap(41, 41, 41)
                                .addComponent(Texto_Clave)
                                .addGap(18, 18, 18)
                                .addComponent(Boton_Agregar))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(LabSin)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Texto_Sinonimo)
                                .addGap(18, 18, 18)
                                .addComponent(Boton_Eliminar)))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addComponent(PanelBusqueda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Boton_Agregar)
                    .addComponent(Texto_Clave, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(LabClave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Boton_Eliminar)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(LabSin)
                        .addComponent(Texto_Sinonimo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(LabBusqueda)
                .addGap(8, 8, 8)
                .addComponent(PanelBusqueda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 316, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }//GEN-END:initComponents

    /** Closes the dialog */
    private void closeDialog(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_closeDialog
        setVisible(false);
        dispose();
    }//GEN-LAST:event_closeDialog

    private void Boton_AgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_AgregarActionPerformed
        if ((!Texto_Clave.getText().isEmpty()) & (!Texto_Sinonimo.getText().isEmpty()) &
            (Texto_Busqueda.getText().isEmpty()))
        {
            regla_negocio.agregarsinonimo(Texto_Clave.getText(), Texto_Sinonimo.getText());
            this.Texto_Clave.setText("");
            this.Texto_Sinonimo.setText("");
            optionPane.showMessageDialog(null, "No Excepcion");
        }
        else
            optionPane.showMessageDialog(null, "Agregar con datos inconsistentes");
    }//GEN-LAST:event_Boton_AgregarActionPerformed
    
    private void Boton_EliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_EliminarActionPerformed
        if ((!Texto_Clave.getText().isEmpty()) & (!Texto_Sinonimo.getText().isEmpty()) &
            (Texto_Busqueda.getText().isEmpty()))
        {
            regla_negocio.eliminarsinonimo(Texto_Clave.getText(), Texto_Sinonimo.getText());
            this.Texto_Clave.setText("");
            this.Texto_Sinonimo.setText("");
            optionPane.showMessageDialog(null, "No Excepcion");
        }
        else
            optionPane.showMessageDialog(null, "Eliminar con datos inconsistentes");
    }//GEN-LAST:event_Boton_EliminarActionPerformed

    private void Boton_BuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_BuscarActionPerformed
        if ((Texto_Clave.getText().isEmpty()) & (Texto_Sinonimo.getText().isEmpty()) &
            (!Texto_Busqueda.getText().isEmpty()))
        {
            DefaultTableModel tabla=regla_negocio.leosinonimo(Texto_Busqueda.getText());
            if(tabla!=null){
            this.Tabla_Sinonimos.setModel(tabla);
            this.Texto_Busqueda.setText("");
            optionPane.showMessageDialog(null, "No Excepcion");}
        }
        else
            optionPane.showMessageDialog(null, "Busqueda con datos inconsistentes");
      }//GEN-LAST:event_Boton_BuscarActionPerformed


    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                DiccionarioGUI dialog = new DiccionarioGUI(new java.awt.Frame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter()
                {
                    public void windowClosing(java.awt.event.WindowEvent e)
                    {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }


    Reglas_de_negocio regla_negocio = new Reglas_de_negocio(); 
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Agregar;
    private javax.swing.JButton Boton_Buscar;
    private javax.swing.JButton Boton_Eliminar;
    private javax.swing.JLabel LabBusqueda;
    private javax.swing.JLabel LabClave;
    private javax.swing.JLabel LabSin;
    private javax.swing.JLabel LabTextBusqueda;
    private javax.swing.JPanel PanelBusqueda;
    private javax.swing.JTable Tabla_Sinonimos;
    private javax.swing.JTextField Texto_Busqueda;
    private javax.swing.JTextField Texto_Clave;
    private javax.swing.JTextField Texto_Sinonimo;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

}
